services:
  suppliers-front:
    build: 
      dockerfile : fronts/suppliers-front.Dockerfile
    ports: 
      - "3000:3000"
  store-front:
    build: 
      dockerfile : fronts/store-front.Dockerfile
    ports: 
      - "3001:3000"
  sso-front:
    build: 
      dockerfile : fronts/sso-front.Dockerfile
    ports:
      - "3002:3000"
  catalog-api:
    build: 
      dockerfile : apis/catalog-api.Dockerfile
    ports:
       - "3500:80"
    depends_on:
       - "postgres-catalog" 
  command-api:
    build: 
      dockerfile : apis/command-api.Dockerfile
    ports:
       - "3600:80"
  postgres-catalog:
    image: postgres:latest
    ports:
      - '27017:27017'
    env_file:
      - 'postgres.env'
  postgres-commands:
    image: postgres:latest
    ports:
      - '27018:27017'
    env_file:
      - 'postgres.env'
