volumes:
  postgres_catalog_volume:
  postgres_command_volume:
  postgres_keycloak_volume:
    driver: local

services:
  postgres-keycloak:
    image: postgres:latest
    volumes:
      - postgres_keycloak_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  postgres-commands:
    image: postgres:latest
    ports:
      - '2346:5432'
    env_file:
      - 'postgres.env'

  postgres-catalog:
    image: postgres:latest
    ports:
      - '2345:5432'
    env_file:
      - 'postgres.env'
    volumes:
      - postgres_catalog_volume:/var/lib/postgresql/data

  suppliers-front:
    build: 
      dockerfile : fronts/suppliers-front.Dockerfile
    ports: 
      - "3000:3000"
    volumes:
      - ./fronts/suppliers-front:/app
      - /app/node_modules
    env_file:
      - '.front.env'
    environment:
      - KEYCLOAK_URL=myurl
      - KEYCLOAK_CLIENT=myclient
      - KEYCLOAK_REALM=myreaml
      - CATALOG_API_URL=//localhost:3500/api

  store-front:
    build: 
      dockerfile : fronts/store-front.Dockerfile
    ports: 
      - "3001:3000"
    volumes:
      - ./fronts/store-front:/app
      - /app/node_modules
    env_file:
      - '.front.env'
    environment:
      - KEYCLOAK_URL=myurl
      - KEYCLOAK_CLIENT=myclient
      - KEYCLOAK_REALM=myreaml
      - CATALOG_API_URL=//localhost:3500/api

  catalog-api:
    build: 
      dockerfile: apis/catalog-api.Dockerfile
    ports:
      - "3500:80"
    depends_on:
      - "postgres-catalog"

  command-api:
    build: 
      dockerfile : apis/command-api.Dockerfile
    ports:
       - "3600:80"

  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres-keycloak
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8080:8080
    depends_on:
      - postgres-keycloak