services:
  suppliers-front:
    build: .
    ports:
      -8001
  store-front:
    build: .
    ports:
      -8002
  sso-front:
    build: .
    ports:
      -8003
  api-catalog:
    build: .
    ports:
      -5001
  postgres-catalog:
    image: postgres:latest
    ports:
      -'27017:27017'
  api-commands:
    build: .
    ports:
      -5002
  postgres-commands:
    image: postgres:latest
    ports:
      -'27018:27017'
  interface-rest-soap:
    build: .
    ports:
      -5003
  keycloak:
    image: quay.io/keycloak/keycloak:latest #TODO: verify ?
    ports:
      - 8004:8080